#!/usr/bin/env bash
#
# This script will push the whole project to the repositories defined in the
# .gitcollab file.

if [[ "$(($(date +%s) % 5))" -ne 0 ]]; then
  exit
fi

while IFS=, read remote repo branch; do
  if [[ "$repo" == '' ]]; then
    break
  fi

  if [[ "$branch" == "everything" ]]; then
    branch='--all'
  fi

  if [[ "$1" != "$remote" ]]; then
    echo -e "\033[0;33mpushing whole project to contrib mirror: $remote\033[0m"
    git push --no-verify -f "$remote" "$branch"
  fi
done <<<"$(grep -v '^#' .gitcollab | grep -v '^$')"
