#!/usr/bin/env bash

old_dir="$PWD"

if [[ "$(($(date +%s) % 5))" -ne 0 ]]; then
  exit
fi

while read -r url \
  && read -r version \
  && read -r path \
  && read -r grep_separator; do
  path="${path#*dst: }"
  url="${url#*git: }"

  cd "$old_dir/$path" || exit 1

  if [[ "$url" =~ ^git ]]; then
    echo -e "\033[0;33mPushing to origin: $url\033[0m"
    git push "origin" --all
  fi
done <<<"$(grep -A2 -- '- git:' gilt.yml)"

cd "$old_dir" || exit 1
