#! /bin/bash
#
# Run automated tests
#
# Usage:
#   {{go}} {{cmd}} [--coverage|--edit|--list] [<glob>...]
#
# Options:
#   --coverage  Collect test coverage data using kcov (Linux only)
#   --edit      Open matching test files using `{{go}} edit`
#   --list      List test suite names without executing them
#
# Without <glob> arguments, runs (or edits, or lists) all tests. With one or
# more <glob> arguments, only runs tests matching 'tests/<glob>.bats'.
#
# If a <glob> doesn't match any test files, the command will return an error
# without running any tests. See `{{go}} help glob` for details.
#
# NOTE: If the <glob> produces errors, or generally doesn't do as you expect,
# you may need to include it in quotes so it isn't expanded by the shell
# _before_ executing the {{cmd}} command.

test_dir="${_HEADSTART_SCRIPT_NAME~~}_TESTS_DIR"
test_dir="${!test_dir}"

function __completions() {

  export GLOBIGNORE="$test_dir/unit/fixtures/*"
  for test_file in "$test_dir/unit"/**/*.bats; do
    test_file="${test_file#"$test_dir/unit/"}"
    echo "${test_file%.bats}"
  done
}
__() {
  bats="$_HEADSTART_CORE_DIR/vendor/bats-core/bin/bats"

  if [[ "$list" ==  'true' ]]; then
    __completions
    return
  fi

  if [[ "${glob[*]}" == '' ]]; then
    read -ar glob <<< "$(__completions)"
  fi

  read -a glob <<< "${glob[*]/%/.bats}"

  cd "$test_dir/unit" || exit 1

  set +eu
  "$bats" "${glob[@]}"
}

__ "$@"
