#!/usr/bin/env bash

GO_ALIAS_CMDS_EXTRA=('nvim' 'vim' 'nano' "${HEADSTART_ALIAS_CMDS_EXTRA[@]}")
GO_ALIAS_EXPAND_CMDS=("${HEADSTART_ALIAS_EXPAND_CMDS[@]}")

if [[ "$EUID" -eq 0 ]]; then
  alias sudo='sudo ' # https://askubuntu.com/questions/22037
else
  alias sudo=' ' # https://askubuntu.com/questions/22037
fi
