#!/usr/bin/env bash
#
## @file
## @author Nikolaos Kakouros <nkak@kth.se>
## @brief Custom functions for the twmn project
## @copyright TODO
##
## Functions that start with 'get_' will return with values.
## Functions that start with 'set_' will set some global variables based on
## input arguments.
## Functions that start with 'read_' will set some global variables based on
## project configuration.

# TODO merge these 'get' functions into one that accepts the ini key as argument
#      and use lib/ini to parse the file
## @fn project_get_gce_project()
## @brief Returns the project name from the project configuration
## @return the project name
##
## \par Note
## The project name, together with other user-supplied information given during
## the installation of the project is stored in \e project.conf.
function project_get_gce_project() {
  local project
  project=""

  if [[ -e "$_HEADSTART_PROJECT_CONFIG" ]]; then
    try {
      grep -E "project ?=" "$_HEADSTART_PROJECT_CONFIG" > /dev/null
    } catch {
      abort "project.conf is corrupted! Rerun '${_HEADSTART_CMD##*/} project setup'"
    }
    project="$(grep -E "project ?=" "$_HEADSTART_PROJECT_CONFIG")"
    project="$(echo "$project" | sed -E 's/[\s\t]*project ?= ?([a-zA-Z0-9-]+)/\1/' | tr -d "[:space:]")"
  fi

  echo "$project"
}


function project_get_world_reuse() {
  local world_reuse=''

  if [[ ! -e "$_HEADSTART_PROJECT_CONFIG" ]]; then
    return "$_HEADSTART_EC_NOTFND"
  fi

  while read -s line; do
    if [[ "$line" =~ ^world_reuse\ ?=\ ?(.*) ]]; then
      world_reuse="${BASH_REMATCH[1]}"
    fi
  done < "$_HEADSTART_PROJECT_CONFIG"

  if [[ -z "$world_reuse" ]]; then
    return "$_HEADSTART_EC_GENERR"
  fi

  echo "$world_reuse"
}

function project_get_user_role() {
  local user_role=''

  if [[ ! -e "$_HEADSTART_PROJECT_CONFIG" ]]; then
    return "$_HEADSTART_EC_NOTFND"
  fi

  while read -s line; do
    if [[ "$line" =~ ^user_role\ ?=\ ?(.*) ]]; then
      user_role="${BASH_REMATCH[1]}"
    fi
  done < "$_HEADSTART_PROJECT_CONFIG"

  if [[ -z "$user_role" ]]; then
    return "$_HEADSTART_EC_GENERR"
  fi

  echo "$user_role"
}
